 version: "2"
 services:
    server:
     container_name: server
     restart: always
     build: ./backend
     ports:
      - "8080:8080"
     depends_on:
      - mongo

    client:
     container_name: client
     restart: always
     build: ./client
     ports: 
      - "3000:3000"
     links:
      - server

    mongo:
     container_name: mongo
     image: mongo
     restart: always
     ports:
     - 27017:27017

    # nginx:
    #  container_name: nginx
    #  image: nginx
    #  ports:
    #   - '80:80'
    #  volumes:
    #   - ./nginx-conf.conf:/etc/nginx/conf.d/default.conf
    #  depends_on:
    #   - server

    

